name: PaperPunish
version: '${version}'

main: de.mcaffe13.paperPunish.PaperPunish
api-version: '1.21.11'
load: STARTUP

authors: [de.mcaffe13]

commands:
  punish:
    description: Use this command to punish a player
    usage: /punish <player> <reason>
    default: op
  smite:
    description: Use this command to send a Lightning Strike on a Player
    usage: /smite <player>
    default: op
  unban:
    description: Use this command to unban Players
    usage: /unban <player>
    default: op